const historySnippets = [
  "In medieval times people were put to death for being witches. One anthropologist conjectures as many as 600,000 'witches' lost their lives.",
  "Mexican General Santa Anna had an elaborate state funeral for his amputated leg.",
  "Before the mid-19th century dentures were commonly made with teeth pulled from the mouths of dead soldiers.",
  "During the Ice Age, Britons used skulls of the dead as cups.",
  "In ancient Egypt, servants were smeared with honey to attract flies away from the pharaoh.",
  "Roman Catholics in Bavaria founded a secret society in 1740 called the Order of the Pug. New members had to wear dog collars and scratch at the door to get in.",
  "Henry VIII of England had people who were called 'Grooms of Stool' whose job it was to wipe his bottom. During his reign, he had four such people, all of whom were knighted.",
  "Before Abraham Lincoln became a politician, he was a champion wrestler. With more than 300 bouts under his belt, Lincoln only lost one match in his career and was inducted into the National Wrestling Hall Of Fame in 1992.",
  "Until the early 20th century in Mongolia, criminals could be locked up in a wooden box as punishment, sometimes left to die of starvation.",
  "In the Victorian era, it was popular for people to photograph relatives after they had died, often placing them in lifelike poses.",
  "In Renaissance France, a woman could take her husband to court if he was impotent.",
  "In 1923, jockey Frank Hayes won a race at Belmont Park in New York despite being dead. He suffered a heart attack mid-race, but his body stayed in the saddle until his horse crossed the line for a 20-1 outsider victory.",
  "All British tanks since 1945 have included equipment to make tea.",
  "Hitler, Mussolini, and Stalin were all nominated for the Nobel Peace Prize.",
  "One of history's most successful pirates was a Chinese prostitute named Ching Shih. She commanded a fleet of over 1,500 ships and 80,000 sailors.",
  "Tsutomu Yamaguchi was in Hiroshima when the first atom bomb was dropped. He then traveled home to Nagasaki the day before the second atom bomb was dropped. He survived both and lived to be 93.",
  "Roman Emperor Gaius, also known as Caligula, made one of his favorite horses a senator.",
  "On his death bed, Voltaire was asked to renounce Satan by a visiting priest. He replied, 'This is no time to be making new enemies'.",
  "The town of Salem, New Jersey once held a trial against tomatoes in 1820 because of the widespread belief they were poisonous. The case ended after Colonel Robert Gibbon Johnson ate a basket of tomatoes without ill consequence.",
  "While Pope Gregory IX was in power, he declared that cats were associated with devil worship and had them exterminated across Europe. It\'s believed that the disappearance of cats helped rats proliferate and spread the bubonic plague.",
  "Jeanette Rankin became the first female member of Congress in America in 1916, four years before women were given the right to vote.",
  "In 1942, the U.S. Army fired 1,400 anti-aircraft rounds during what was thought to be a Japanese air raid over Los Angeles County. It turned out to be a false alarm. Five civilians died as an indirect result.",
  "In 1493, Columbus thought he saw mermaids -- they were 'not as pretty as they are depicted, for somehow in the face they look like men.' It\'s suspected he saw a manatee.",
  "At the height of his popularity, Charlie Chaplin entered a Charlie Chaplin look-a-like competition in San Francisco. He came in 20th place.",
  "Chickens may have been first domesticated by humans for cockfighting, not for food.",
  "History's shortest war was the Anglo-Zanzibar War, fought between Great Britain and the Zanzibar Sultanate in 1896. It lasted approximately 40 minutes, and Britain's victory was the end of Zanzibar Sultanate as a sovereign state and the start heavy British influence.",
  "During the 1800s in the United States, it was considered a cruel and unusual punishment to feed lobster to prisoners and convicts.",
  "Fourteen years before the Titanic sank, Morgan Robertson wrote the novella Futility. It was about the large unsinkable ship 'Titan' hitting an iceberg in the Northern Atlantic. Both the Titanic and the fictional Titan did not have enough lifeboats for the thousands of passengers on board.",
  "In 1998, 1,200 bones from some ten human bodies were found in the basement of Ben Franklin\'s house. The bodies were used in the study of human anatomy, scholars believe.",
  "Between the 11th and 19th centuries, Buddhist monks in northern Japan practiced a kind of meditation called Sokushinbutsu, in which they would mummify themselves alive by slowly weaning themselves off food and water before eventually starving to death.",
  "Seven of the ten deadliest wars in human history have been in China.",
  "The Taiping Rebellion in China, a revolt against the Qing dynasty fought from 1850 to 1864, led to more deaths than World War I.",
  "Between 1900 and 1920, Tug of War was an Olympic event. It was contested as a part of the track and field program.",
  "Thomas Jefferson and John Adams died hours apart on the same day, July 4, 1826, the 50th anniversary of American independence.",
  "During World War II, a Pennsylvania dentist convinced President Roosevelt to bomb Japan with timed explosives attached to thousands of bats. But after some of the armed bats were accidentally released and destroyed their testing facility, the bat bomb project was scrapped.",
  "President William Henry Harrison served the shortest term in U.S. history. He died of a cold just two months into his presidency. Doctors gave him traditional treatments like leeches, opium, and snakeweed, which contributed to his death.",
  "In 1945, a balloon bomb launched by Japan landed in Oregon. It was happened upon by a woman and five children, who died when it exploded. These were the only World War 2 casualties on US soil after America entered the war.",
  "Serial killer Ted Bundy once saved a young child from drowning and also received a commendation from the Seattle Police Department for chasing down a purse snatcher.",
  "Instead of saying 'cheese,' Victorians said 'prunes' when their picture was about to be taken.",
  "The current 50 star U.S. flag was designed by 17-year-old Robert Heft for a school project. He received a B-.",
  "In 1838, Edgar Allan Poe wrote The Narrative of Arthur Gordon Pym of Nantucket, a book about four crewmen on a whaling ship who ended up stranded and having to draw lots to see who would be eaten. The lot landed on a cabin boy named Richard Parker. Forty-six years later, a yacht named Mignonette bound for Sydney, Australia capsized en route from London. The three crewmen then killed and ate their cabin boy named Richard Parker.",
  "People were buried alive so often in the 19th century that a safety coffin was invented so the 'dead' would have the ability to alert those above ground if they were still alive.",
  "Civil War soldiers on both sides were offered bounties upon enlistment, causing some men to enlist and escape again and again in order to collect multiple bounties. One man collected 32 before he was finally caught.",
  "John Wilkes Booth shot and killed Abraham Lincoln in a Washington theater in April 1865. Booth was a Confederate sympathizer who believed slavery was 'one of the greatest blessings... God ever bestowed upon a favored nation.'",
  "The oldest known printed text originated in China during the first millennium A.D. The Diamond Sutra, a Buddhist book from Dunhuang, China from around 868 A.D.during the Tang Dynasty, is the oldest known printed book.",
  "China's earliest archeological records date back to the Shang Dynasty (1600–1046 BC), over 3,000 years ago. Before then, there were almost 2,000 years of prehistoric times, without written history.",
  "China's first imperial dynasty was the Qin dynasty (221–206 BC), and the last dynasty was the Qing dynasty (1644–1912). The whole period is known as China's imperial feudal period.",
  "China was the first country in the world to use paper money. The first type of paper money was called jiaozi (Chinese: 交子), printed in 1023 during the Northern Song dynasty in Chengdu, the capital of Sichuan Province.",
  "As legend has it, Rome was founded in 753 B.C. by Romulus and Remus, twin sons of Mars, the god of war. Left to drown in a basket on the Tiber by a king and rescued by a she-wolf, the twins lived to defeat that king and found their own city on the river’s banks in 753 B.C. After killing his brother, Romulus became the first king of Rome, which is named for him.",
  "Rome was built on seven hills — Esquiline Hill, Palatine Hill, Aventine Hill, Capitoline Hill, Quirinal Hill, Viminal Hill and Caelian Hill.",
  "Julius Caesar was murdered on the ides of March (March 15, 44 B.C.) by a group of his enemies led by the republican nobles Marcus Junius Brutus and Gaius Cassius. Consul Mark Antony and Caesar’s great-nephew and adopted heir, Octavian, then joined forces to crush Brutus and Cassius.",
  "The French Revolution was a period of social and political upheaval from 1789 to 1799, caused by widespread discontent with the French monarchy and the poor economic policies of King Louis XVI. The Revolution resulted in the execution of Louis XVI and his wife, Marie Antoinette. It was also during this time that Napoleon I began gaining power, rapidly rising through the ranks of the military.",
  "At the outset of the 20th century, Japan, China and Russia vied for control over the Korean Peninsula. Following the Russo-Japanese War, Japan emerged the victor and began occupying the peninsula in 1905, formally annexing it five years later.",
  "After Japan’s defeat during WWII in 1945, the United States and the Soviet Union divided the Korean peninsula into two zones of influence. In 1948, the pro-U.S. Republic of Korea (South Korea) was established in Seoul, led by the strongly anti-communist Syngman Rhee. In the north, the Soviets installed Kim Il Sung as the first premier of the Democratic People’s Republic of Korea (DPRK)."
];

const historySnippet = () => {
  return historySnippets[ Math.floor(Math.random() * historySnippets.length) ];
};
