function historySnippet() {
  const hisP = document.getElementById("his-snippet");

  const historySnippets = [
    "The Ottoman Empire's Sultan Ibrahim I had 280 of his concubines drowned in the ocean after one of them slept with another man.",
    "In medieval times people were put to death for being witches. One anthropologist conjectures as many as 600,000 'witches' lost their lives.",
    "Mexican General Santa Anna had an elaborate state funeral for his amputated leg.",
    "Before the mid-19th century dentures were commonly made with teeth pulled from the mouths of dead soldiers.",
    "Ice age Britons used skulls of the dead as cups.",
    "In 1926, Arctic explorer Peter Freuchen was trapped under an avalanche while on an expedition. He escaped from death by fashioning a shiv out of his own feces and amputating his foot.",
    "In ancient Egypt, servants were smeared with honey to attract flies away from the pharaoh.",
    "Roman Catholics in Bavaria founded a secret society in 1740 called the Order of the Pug. New members had to wear dog collars and scratch at the door to get in.",
    "The first fax was sent while people were still traveling the Oregon Trail.",
    "Henry VIII of England had people who were called 'Grooms of Stool' whose job it was to wipe his bottom. During his reign, he had four such people, all of whom were knighted.",
    "Before Abraham Lincoln became a politician, he was a champion wrestler. With more than 300 bouts under his belt, Lincoln only lost one match in his career and was inducted into the National Wrestling Hall Of Fame in 1992.",
    "Until the early 20th century in Mongolia, criminals could be locked up in a wooden box as punishment, sometimes left to die of starvation.",
    "In the Victorian era, it was popular for people to photograph relatives after they had died, often placing them in lifelike poses.",
    "In Renaissance France, a woman could take her husband to court if he was impotent.",
    "In 1923, jockey Frank Hayes won a race at Belmont Park in New York despite being dead. He suffered a heart attack mid-race, but his body stayed in the saddle until his horse crossed the line for a 20-1 outsider victory.",
    "All British tanks since 1945 have included equipment to make tea.",
    "Hitler, Mussolini, and Stalin were all nominated for the Nobel Peace Prize.",
    "One of history's most successful pirates was a Chinese prostitute named Ching Shih. She commanded a fleet of over 1,500 ships and 80,000 sailors.",
    "Tsutomu Yamaguchi was in Hiroshima when the first atom bomb was dropped. He then traveled home to Nagasaki the day before the second atom bomb was dropped. He survived both and lived to be 93.",
    "Roman Emperor Gaius, also known as Caligula, made one of his favorite horses a senator.",
    "On his death bed, Voltaire was asked to renounce Satan by a visiting priest. He replied, 'This is no time to be making new enemies'.",
    "The town of Salem, New Jersey once held a trial against tomatoes in 1820 because of the widespread belief they were poisonous. The case ended after Colonel Robert Gibbon Johnson ate a basket of tomatoes without ill consequence.",
    "While Pope Gregory IX was in power, he declared that cats were associated with devil worship and had them exterminated across Europe. It\'s believed that the disappearance of cats helped rats proliferate and spread the bubonic plague.",
    "Jeanette Rankin became the first female member of Congress in America in 1916, four years before women were given the right to vote.",
    "Despite popular rumors, Elvis Presley had severe constipation that plagued him throughout his life. He actually died while pooping because of a condition called megacolon.",
    "In 1942, the U.S. Army fired 1,400 anti-aircraft rounds during what was thought to be a Japanese air raid over Los Angeles County. It turned out to be a false alarm. Five civilians died as an indirect result.",
    "In 1493, Columbus thought he saw mermaids -- they were 'not as pretty as they are depicted, for somehow in the face they look like men.' It\'s suspected he saw a manatee.",
    "At the height of his popularity, Charlie Chaplin entered a Charlie Chaplin look-a-like competition in San Francisco. He came in 20th place.",
    "Chickens may have been first domesticated by humans for cockfighting, not for food.",
    "History's shortest war was between England and Zanzibar. It lasted only 38 minutes.",
    "During the 1800s in the United States, it was considered a cruel and unusual punishment to feed lobster to prisoners and convicts.",
    "Fourteen years before the Titanic sank, Morgan Robertson wrote the novella Futility. It was about the large unsinkable ship 'Titan' hitting an iceberg in the Northern Atlantic. Both the Titanic and the fictional Titan did not have enough lifeboats for the thousands of passengers on board.",
    "Thomas Edison once electrocuted a circus elephant to death on Coney Island. Over a thousand people came to watch her die while Edison recorded it on video.",
    "In 1998, 1,200 bones from some ten human bodies were found in the basement of Ben Franklin\'s house. The bodies were used in the study of human anatomy, scholars believe.",
    "Between the 11th and 19th centuries, Buddhist monks in northern Japan practiced a kind of meditation called Sokushinbutsu, in which they would mummify themselves alive by slowly weaning themselves off food and water before eventually starving to death.",
    "Seven of the ten deadliest wars in human history have been in China.",
    "The Taiping Rebellion in China (1850 to 1864) alone had twice as many deaths as World War 1.",
    "Between 1900 and 1920, Tug of War was an Olympic event.",
    "During the middle ages, it was believed that sperm produced from the left testicle produced girls. To ensure having a son, men would have it removed.",
    "Thomas Jefferson and John Adams died hours apart on the same day, July 4, 1826, the 50th anniversary of American independence.",
    "During World War II, a Pennsylvania dentist convinced President Roosevelt to bomb Japan with timed explosives attached to thousands of bats. But after some of the armed bats were accidentally released and destroyed their testing facility, the bat bomb project was scrapped.",
    "The smallest Major League Baseball player of all time was 3foot 7inches Eddie Gaedel. He walked in his only plate appearance.",
    "President William Henry Harrison served the shortest term in U.S. history. He died of a cold just two months into his presidency. Doctors gave him traditional treatments like leeches, opium, and snakeweed, which contributed to his death.",
    "In 1945, a balloon bomb launched by Japan landed in Oregon. It was happened upon by a woman and five children, who died when it exploded. These were the only World War 2 casualties on US soil after America entered the war.",
    "Serial killer Ted Bundy once saved a young child from drowning and also received a commendation from the Seattle Police Department for chasing down a purse snatcher.",
    "Instead of saying 'cheese,' Victorians said 'prunes' when their picture was about to be taken.",
    "The Civil War began on the farm of Wilmer McLean, who then moved more than a hundred miles away to escape the fighting, only to have the war end inside his new house at Appomattox.",
    "Romans used urine as mouthwash. Urine contains ammonia, which is one of the best natural cleaning agents on the planet.",
    "The current 50 star U.S. flag was designed by 17-year-old Robert Heft for a school project. He received a B-.",
    "A passenger who lived through the traumatic fire and sinking of a ship in 1871 faced his fears and boarded the Titanic in 1912. He sank with the ship.",
    "In 1838, Edgar Allan Poe wrote The Narrative of Arthur Gordon Pym of Nantucket, a book about four crewmen on a whaling ship who ended up stranded and having to draw lots to see who would be eaten. The lot landed on a cabin boy named Richard Parker. Forty-six years later, a yacht named Mignonette bound for Sydney, Australia capsized en route from London. The three crewmen then killed and ate their cabin boy named Richard Parker.",
    "A would-be assassin threw a grenade at George W. Bush in 2005, but it didn\'t explode.",
    "People were buried alive so often in the 19th century that a safety coffin was invented so the 'dead' would have the ability to alert those above ground if they were still alive.",
    "Civil War soldiers on both sides were offered bounties upon enlistment, causing some men to enlist and escape again and again in order to collect multiple bounties. One man collected 32 before he was finally caught.",
    "Lord Byron kept a pet bear in his dorm room while studying at Cambridge University."
  ];

  hisP.innerHTML = historySnippets[ Math.floor( Math.random() * historySnippets.length ) ];
}

historySnippet();
